export const FETCH_PLATFORMS_REQUEST = "FETCH_PLATFORMS_REQUEST";
export const FETCH_PLATFORMS_SUCCESS = "FETCH_PLATFORMS_SUCCESS";
export const FETCH_PLATFORMS_FAILURE = "FETCH_PLATFORMS_FAILURE";
export const SELECT_PLATFORM_FILTER = "SELECT_PLATFORM_FILTER";