export const FETCH_GAMES_REQUEST = "FETCH_GAMES_REQUEST";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAILURE = "FETCH_GAMES_FAILURE";
export const UPDATE_GAMES_FILTERS = "UPDATE_GAMES_FILTERS";

export const FETCH_GAME_REQUEST = "FETCH_GAME_REQUEST";
export const FETCH_GAME_SUCCESS = "FETCH_GAME_SUCCESS";
export const FETCH_GAME_FAILURE = "FETCH_GAME_FAILURE";


export const FETCH_SCREEN_GAME_REQUEST = "FETCH_SCREEN_GAME_REQUEST";
export const FETCH_SCREEN_GAME_SUCESS = "FETCH_SCREEN_GAME_SUCESS";
export const FETCH_SCREEN_GAME_FAILURE = "FETCH_SCREEN_GAME_FAILURE";